# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-27 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileInfoModel',
            new_name='ModelToAddStuffToInBuiltUserModel',
        ),
    ]
